# Sopstvene vrednosti i sopstveni vektori matrice

Kvadratna matrica $A$ ima sopstveni vektor $x$ i sopstvenu vrednost $\lambda$, ukoliko važi $Ax = \lambda x$, $x \ne 0$. Poznato je da različitim sopstvenim vrednostima odgovaraju linearno nezavisni sopstveni vektori, kao i da su sopstvene vrednosti jednake nulama karakterističnog polinoma $\det(A − \lambda I)$.

Geometrijski, sopstveni vektori su vektori koji u transformaciji indukovanoj maticom A ne menjaju svoj pravac. Smer i dužina vektora se mogu promeniti i tu promenu reflektuje sopstvena vrednost. Na slici, na primer, plavi i ljubičasti vektori odgovaraju pravcima sopstvenih vektora.

<img src='assets/eigenvectors.gif'>

In [1]:
import numpy as np
from numpy import linalg as LA

Podsetimo se da funkcija `eig` paketa `numpy.linalg` vraća niz sopstvenih vrednosti i matricu sopstvenih vektora. Sopstveni vektori su u matrici predstavljeni kolonama pri čemu je $i$-ta kolona u matrici sopstveni vektor koji odgovara $i$-toj sopstvenoj vrednosti u nizu.

In [2]:
A = np.array([[0.5, 0.5], [0.2, 0.8]])

In [3]:
A

array([[0.5, 0.5],
       [0.2, 0.8]])

In [4]:
values, vectors = LA.eig(A)

Sopestvene vrednosti:

In [5]:
values

array([0.3, 1. ])

Sopstveni vektori:

In [6]:
vectors

array([[-0.92847669, -0.70710678],
       [ 0.37139068, -0.70710678]])

Vektori koji se dobijaju na ovaj način su normalizovani:

In [7]:
LA.norm(vectors[:, 0])

1.0

In [8]:
LA.norm(vectors[:, 1])

0.9999999999999999

Nadalje će biti prikazani neki algoritmi koji se mogu iskoristit za određivanje sopstvenih vektora i vrednosti zadate matrice.

### Metoda stepenovanja

Neka je $b_{0}$ proizvoljno generisan vektor koji ne sadrži nule i neka je $$b_{k+1}=\frac {Ab_{k}}{||Ab_{k}||}.$$ Dakle, u svakoj iteraciji se vektor $b_{k}$ množi matricom $A$ i normalizuje. Pretpostavimo da sopstvenim vrednostima matrice $A$, za koje važi $|\lambda_1|>|\lambda_2|>\dots>|\lambda_n|$, odgovaraju sopstveni vektori $x_1, x_2, \dots, x_n$. Tada vektori $b_{k}$ kroz iteracije čine niz koji konvergira ka $x_1$, odnosno sopstvenom vektoru koji odgovara sopstvenoj vrednosti čija je apsolutna vrednost najveća. Opisani algoritam se naziva `metoda stepenovanja` i pomoću njega se može pronaći najveća po apsolutnoj vrednosti sopstvena vrednost i njoj odgovarajući sopstveni vektor. Za nalaženje sopstvene vrednosti $\lambda_1$, ako je poznat vektor $x_1$, dovoljno je primetiti da iz $Ax_1 = \lambda_1x_1$ sledi $x_1^TAx_1 = x_1^T\lambda_1x_1$, odakle je $$\lambda_1 = \frac{x_1^TAx_1}{x_1^Tx_1}.$$ I u brojiocu i u imeniocu proizvod matrice i vektora je skalar.

In [9]:
def power_method(A, number_of_iterations):
    
    N = A.shape[0]
    
    b = np.random.rand(N)
    
    for _ in range(number_of_iterations):
        b = np.dot(A, b) / np.linalg.norm(np.dot(A, b))
        
    
    b_lambda = b.T.dot(A).dot(b)/(b.T.dot(b))
        
    return b_lambda, b

In [10]:
power_method(A, 50)

(1.0, array([0.70710678, 0.70710678]))

### Metoda iscrpljivanja

Pretpostavimo da sopstvenim vrednostima matrice $A$, za koje važi $|\lambda_1|>|\lambda_2|>\dots>|\lambda_n|$, odgovaraju sopstveni vektori $x_1, x_2, \dots, x_n$. Neka su $y_1, y_2, \dots, y_n$ sopstveni vektori koji odgovaraju matrici $A^{T}$. Neka je $A_1 = A$ i $$A_{i+1} = A_i - \lambda_ix_iy_i^T.$$ Odgovarajuće sopstvene vrednosti i sopstveni vektori se u svakoj iteraciji dobijaju redom primenom metoda stepenovanja na matrice $A_i$ i $A_i^T$. Time se, kao izlaz iz algoritma, mogu generisati sve sopstvene vrednosti i svi sopstveni vektori polazne matrice. Opisani metod se naziva `metod iscrpljivanja`.

In [11]:
def exhausting_method(A, number_of_vectors, number_of_iterations):
    
    # nizovi sopstvenih vrednosti i vektora
    values = []
    vectors = []
    
    N = A.shape[0]
    
    for i in range(N):
        x_lambda, x = power_method(A, number_of_iterations)
        y_lambda, y = power_method(A.T, number_of_iterations)
        
        values.append(x_lambda)
        vectors.append(x)
        
        x = x.reshape(N, 1)
        y = y.reshape(N, 1)
        
        A = A - x_lambda * np.dot(x, y.T)
        
    return values, vectors

In [12]:
values, vectors = exhausting_method(A, 2, 50)

In [13]:
values

[1.0, 0.3]

In [14]:
vectors

[array([0.70710678, 0.70710678]), array([-0.92847669,  0.37139068])]

Napomenimo još da obe opisane metode nalaze aproksimaciju rešenja. Greška se može smanjiti dovoljnim brojem iteracija, mada je tada algoritam nešto sporiji. Nekada je konvergencija ka rešenju sporija, a nekada brža. 